<?php

session_start();

include "config/config.php";
include "include/ldap_connection.inc";
include "logon.php";

include "include/header_noimg.inc";

switch($_POST['action']) {
	case "add":
	
	  $pieces=explode("@",$_POST['mail']);
	  $domain_dn=domain_dnparse($_POST['domain']);
//	  $domain_dn=domain_dnparse($pieces[1]);

	  $dn="cn=".$pieces[0].",".$domain_dn.",ou=Aliases,".$config['ldapdn'];
	
      include "templates/inetmailuser-alias.inc";

		$ret=@ldap_add($conn,$dn,$info);
		if($ret){
			echo "<script>
				alert('Alias adicionado com sucesso');
				opener.location.reload();
				self.close();
		  	      </script>";
		}else{
			echo "<script>
				alert('Erro ao adicionar alias: (".ldap_error($conn).")');
				self.close();
			      </script>";
		}
	break;
	default:
		include "html/aliasaddform.phtml";
	break;
}

?>
