<body class="pop" onload="opener.location.reload()">
<div id="formDomainUser">

<form name="adduser" method="POST" action="aliasadd.phtml">
<input type="hidden" name="action" value="add">
<input type="hidden" name="domain" value="<?php echo $_SESSION['domain']; ?>" />

<div class="poptitle">Adicionar Alias</div>
<br/>
<table id="formIntDomainUser">
	<tr>
	 <td valign="top">
 	  <table>
		  <tr>
		   <td colspan="2" class="popsubtitle">Novo Alias</td>
  		  </tr>
 		  <tr>
  			<td style="padding: 5px;">E-mail Alias:</td>
  			<td><input type="text" name="mail"></td>
 		  <tr>
  			<td style="padding: 5px;" >Descri&ccedil;&atilde;o:</td>
  			<td><input type="text" name="sn" />
  			</td>
 		  </tr>
 		  <tr>
  			<td style="padding: 5px;" >Encaminha para:</td>
  			<td><textarea name="mailforwardingaddress" rows="4" cols="32"></textarea>
  			</td>
 		  </tr>
 	 </table>
   </td>
  </tr>
 </table>
 <table align="center" style="padding: 5px;">
 <tr>
   <td><INPUT class="button" type="submit" value="Adicionar"></td>
   <td><INPUT class="button" type="button" value="Cancel" onclick="self.close()"></td>
 </tr>
</table>
</form>
</div>
</body>
</html>
