<body class="pop" onload="opener.location.reload()">
<div id="formDomainUser">

<form name="adduser" method="POST" action="domainadd.phtml">
<input type="hidden" name="action" value="add">

<div class="poptitle">Adicionar Dom&iacute;nio</div>
<br/>
<table id="formIntDomainUser">
	<tr>
	 <td valign="top">
 	  <table>
		  <tr>
		   <td colspan="2" class="popsubtitle">Novo dominio</td>
  		  </tr>
 		  <tr>
  			<td style="padding: 5px;">Dominio:</td>
  			<td><input type="text" name="domain"></td>
 		  <tr>
  			<td style="padding: 5px;" >Descri&ccedil;&atilde;o:</td>
  			<td><input type="text" name="description" />
  			</td>
 		  </tr>
 	 </table>
   </td>
  </tr>
 </table>
 <table align="center" style="padding: 5px;">
 <tr>
   <td><INPUT class="button" type="submit" value="Adicionar"></td>
   <td><INPUT class="button" type="button" value="Cancel" onclick="self.close()"></td>
 </tr>
</table>
</form>
</div>
</body>
</html>
